Simple webpage using anime.js
DSC-ASEB/Hacktoberfest pull request #21
Opened 2021-10-27 14:40 UTC by Shrenik811rp

Webpage made using anime.js with scrolling effect.

2021-10-30 15:22 UTC, VinayakTekade approved these changes

2021-10-30 17:13 UTC, aravindvnair99 requested changes
@Shrenik811rp I switched the library you included to its CDN. Could you [compress your images](https://compresspng.com)? Apart from that, looks good to me.

2021-10-31 08:03 UTC, aravindvnair99 commented
Hey @Shrenik811rp!

Just a reminder... Today is the last date for Hacktoberfest.

2021-11-06 07:00 UTC, aravindvnair99 approved these changes
@Shrenik811rp I have compressed your images for you as you didn't do it. Make sure to keep things optimised next time.

2021-11-06 07:04 UTC, kaazima approved these changes

2021-11-06 07:05 UTC, merged