Added printing patterns in C++
DSC-ASEB/Hacktoberfest pull request #27
Opened 2021-10-30 09:18 UTC by VinayakTekade

Signed-off-by: VinayakTekade <39454332+VinayakTekade@users.noreply.github.com>

## Proposed Changes
- Added 25 patterns

2021-10-30 15:22 UTC, aravindvnair99 requested changes
@VinayakTekade Output doesn't print to console.

2021-10-30 15:22 UTC, aravindvnair99 commented on C++/patterns/binaryHalfPyramid.cpp
> +#endif
```suggestion
```

CodeChef judging content need not be added

2021-10-30 15:22 UTC, aravindvnair99 commented on C++/patterns/diamondInscribedRectangle.cpp
> +#endif
```suggestion
```

2021-10-30 15:26 UTC, VinayakTekade commented
@aravindvnair99 Removed it. That's just a preference I have to take input and output from txt files.

2021-10-30 15:48 UTC, aravindvnair99 requested changes
> @aravindvnair99 Removed it. That's just a preference I have to take input and output from txt files.

Yes @VinayakTekade, but to keep the repository beginner friendly, we could use console input from the user and output there itself instead of file input and output operations.

Could you also add some helper text for all `cin` as a user might not know that input is required?

2021-10-31 06:09 UTC, VinayakTekade commented
@aravindvnair99 Added helper text for inputs.

2021-10-31 06:39 UTC, aravindvnair99 approved these changes

2021-10-31 06:40 UTC, merged